/* Copied from <gdk/gdkkeysyms.h> */
#define GDK_AE 0x0c6
#define GDK_Adiaeresis 0x0c4
#define GDK_Aring 0x0c5
#define GDK_Eacute 0x0c9
#define GDK_Ntilde 0x0d1
#define GDK_Odiaeresis 0x0d6
#define GDK_Ooblique 0x0d8
#define GDK_Udiaeresis 0x0dc
#define GDK_acircumflex 0x0e2
#define GDK_acute 0x0b4
#define GDK_adiaeresis 0x0e4
#define GDK_ae 0x0e6
#define GDK_agrave 0x0e0
#define GDK_aring 0x0e5
#define GDK_bar 0x07c
#define GDK_ccedilla 0x0e7
#define GDK_degree 0x0b0
#define GDK_diaeresis 0x0a8
#define GDK_eacute 0x0e9
#define GDK_ecircumflex 0x0ea
#define GDK_egrave 0x0e8
#define GDK_exclamdown 0x0a1
#define GDK_icircumflex 0x0ee
#define GDK_igrave 0x0ec
#define GDK_ntilde 0x0f1
#define GDK_ocircumflex 0x0f4
#define GDK_odiaeresis 0x0f6
#define GDK_ograve 0x0f2
#define GDK_onehalf 0x0bd
#define GDK_onequarter 0x0bc
#define GDK_oslash 0x0f8
#define GDK_questiondown 0x0bf
#define GDK_section 0x0a7
#define GDK_ssharp 0x0df
#define GDK_sterling 0x0a3
#define GDK_threequarters 0x0be
#define GDK_ucircumflex 0x0fb
#define GDK_udiaeresis 0x0fc
#define GDK_ugrave 0x0f9
#define GDK_ydiaeresis 0x0ff
